import { toast } from 'sonner';

export function getPlainText(markdown: string): string {
  return markdown
    .replace(/#{1,6}\s+/g, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`(.*?)`/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, '$1')
    .replace(/^[-*+]\s+/gm, '• ')
    .replace(/^\d+\.\s+/gm, '')
    .replace(/\|/g, ' ')
    .replace(/^[-:]+$/gm, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

export function shareViaEmail(subject: string, content: string) {
  const plainText = getPlainText(content);
  const body = `${plainText}\n\n—\nGenerated by AroMi AI Health Coach`;
  const mailto = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  window.open(mailto, '_blank');
}

export function copyToClipboard(content: string) {
  const plainText = getPlainText(content);
  navigator.clipboard.writeText(plainText).then(
    () => toast.success('Copied to clipboard!'),
    () => toast.error('Failed to copy')
  );
}

export function downloadAsPDF(contentId: string) {
  const el = document.getElementById(contentId);
  if (!el) return;
  el.classList.add('print-target');
  window.print();
  setTimeout(() => el.classList.remove('print-target'), 500);
}
